--
-- Corner cases for DDL deparsing of CREATE TABLE.
--
-- test_ddl_deparse intercepts each supported command, runs the original in a
-- subtransaction that is rolled back, deparses the collected command, and
-- executes the reconstruction for real.  The deparsed text is reported as a
-- NOTICE, so the expected output pins it.
--
-- Ordinary syntax is not repeated here.  001_deparse_regress.pl replays the
-- whole core regression suite through the deparser and covers that, reporting
-- any divergence as a regression diff.  What a replay cannot see is a change
-- in the deparsed text that leaves the catalogs as they were, since the state
-- it arrives at is the same either way.  The cases below are the ones whose
-- rule is of that kind, plus the few the core tests contain no statement for.
--
-- The event triggers created by the test_ddl_deparse script, which runs
-- first in this schedule, are still installed.  Their "DDL test:" NOTICEs
-- appear below too.
--
LOAD 'test_ddl_deparse';
SET test_ddl_deparse.execute_deparsed_ddl = on;
SET test_ddl_deparse.print_deparsed_ddl = text;

CREATE SCHEMA deparse_tests;

-- A serial column is emitted as the user spelled it.  Expanding it into an
-- integer column plus a sequence, or normalizing serial4 to serial, arrives at
-- the same catalog state.
CREATE TABLE deparse_tests.t_serial (
a serial,
b serial4,
c bigserial,
d smallserial
);

-- COMPRESSION and STORAGE are emitted only where the user wrote them.
-- Emitting the effective value instead would leave attcompression and
-- attstorage exactly as they are.
CREATE TABLE deparse_tests.t_options (
a text COMPRESSION pglz,
b text COMPRESSION default,
c text STORAGE external,
d text STORAGE main,
e text
);
SELECT attname, attcompression, attstorage
  FROM pg_attribute
  WHERE attrelid = 'deparse_tests.t_options'::regclass AND attnum > 0
  ORDER BY attnum;

-- A constraint the user did not name comes back unnamed, so that the replay
-- derives the name the way the original did.  The derived name is the same
-- either way, so the catalogs match whether or not the name is emitted.
-- Inline constraints are normalized to table constraints.
CREATE TABLE deparse_tests.t_constr (
a int PRIMARY KEY,
b int REFERENCES deparse_tests.t_constr (a) NOT NULL,
c text DEFAULT 'x' CHECK (c <> ''),
CONSTRAINT named_check CHECK (a > 0)
);
SELECT conname, contype, pg_get_constraintdef(oid)
  FROM pg_constraint
  WHERE conrelid = 'deparse_tests.t_constr'::regclass
  ORDER BY conname COLLATE "C";

-- A DEFAULT whose cooked expression is a plain NULL constant is not stored in
-- pg_attrdef, so dropping it from the output would leave atthasdef unset too.
CREATE TABLE deparse_tests.t_defnull (a int DEFAULT NULL, b text DEFAULT NULL::text);

-- The temp schema is emitted as pg_temp rather than as this backend's own
-- pg_temp_<n>, which would resolve to the same schema on replay.
CREATE TEMP TABLE t_temp (a int);
DROP TABLE t_temp;

-- Identity sequence options that parse analysis consumes are still in the raw
-- tree.  SEQUENCE NAME has to be emitted; OWNED BY is dropped, since
-- execution overrides it.  The core tests use neither.
CREATE TABLE deparse_tests.t_seqname (
id int GENERATED ALWAYS AS IDENTITY
	(SEQUENCE NAME deparse_tests.t_seqname_seq START WITH 5)
);
SELECT relname FROM pg_class WHERE oid = 'deparse_tests.t_seqname_seq'::regclass;
CREATE TABLE deparse_tests.t_ownedby (
id int GENERATED BY DEFAULT AS IDENTITY (OWNED BY NONE)
);

-- Types whose typmod is spelled inside the name.  The core tests have no
-- column of either type.
CREATE TABLE deparse_tests.t_types (
a interval hour to minute,
b timestamp(3) with time zone
);

-- A LIKE clause is expanded against the source table before execution, so the
-- columns it contributes come back from the catalog.  Emitting the LIKE clause
-- verbatim instead would build the same table wherever the source exists.
CREATE TABLE deparse_tests.t_like_src (
a int NOT NULL,
b text COLLATE "C",
c numeric(10,2) STORAGE plain,
d int DEFAULT 7,
e int GENERATED ALWAYS AS (d * 2) STORED
);
CREATE TABLE deparse_tests.t_like (LIKE deparse_tests.t_like_src);

-- written-out and LIKE columns interleave in catalog order
CREATE TABLE deparse_tests.t_like_mixed (
x serial,
LIKE deparse_tests.t_like_src,
y int DEFAULT 1
);

-- the options that land in the table definition are all recovered
CREATE TABLE deparse_tests.t_like_incl (
LIKE deparse_tests.t_like_src
	INCLUDING DEFAULTS INCLUDING GENERATED INCLUDING CONSTRAINTS
	INCLUDING STORAGE INCLUDING COMPRESSION
);

-- identity comes back with the sequence parameters that were copied
CREATE TABLE deparse_tests.t_like_idsrc (
a int GENERATED BY DEFAULT AS IDENTITY (START WITH 10 INCREMENT BY 5)
);
CREATE TABLE deparse_tests.t_like_ident
  (LIKE deparse_tests.t_like_idsrc INCLUDING IDENTITY);

-- LIKE options that copy a separate object are declined
CREATE INDEX ON deparse_tests.t_like_src (a);
CREATE TABLE deparse_tests.t_like_idx
  (LIKE deparse_tests.t_like_src INCLUDING INDEXES);
CREATE TABLE deparse_tests.t_like_all
  (LIKE deparse_tests.t_like_src INCLUDING ALL);

-- USING INDEX TABLESPACE stays with the constraint that carried it, including
-- after parse analysis has merged redundant constraints.  Every index here
-- lands in pg_default either way, so a misattribution is invisible in the
-- catalogs.
CREATE TABLE deparse_tests.t_idxtblspc (
a int,
b int,
c int,
UNIQUE (a),
UNIQUE (b) USING INDEX TABLESPACE pg_default,
PRIMARY KEY (c)
);
CREATE TABLE deparse_tests.t_dedup (
a int,
b int,
UNIQUE (a),
UNIQUE (a),
UNIQUE (b) USING INDEX TABLESPACE pg_default,
PRIMARY KEY (a)
);

-- Index storage parameters of an index-backed constraint, which
-- pg_get_constraintdef omits for PRIMARY KEY and UNIQUE but already includes
-- for EXCLUDE.  No constraint in the core tests carries them.
CREATE TABLE deparse_tests.t_idxopts (
a int,
b int,
UNIQUE (a) WITH (fillfactor = 90),
PRIMARY KEY (b) WITH (fillfactor = 80, deduplicate_items = off)
	USING INDEX TABLESPACE pg_default DEFERRABLE
);
SELECT c.relname, c.reloptions
  FROM pg_class c
  WHERE c.relname IN ('t_idxopts_a_key', 't_idxopts_pkey')
  ORDER BY 1;
CREATE TABLE deparse_tests.t_exclopts (
c circle,
EXCLUDE USING gist (c WITH &&) WITH (fillfactor = 70)
	USING INDEX TABLESPACE pg_default DEFERRABLE
);
SELECT c.relname, c.reloptions
  FROM pg_class c
  JOIN pg_constraint con ON con.conindid = c.oid
  WHERE con.conrelid = 'deparse_tests.t_exclopts'::regclass;

-- An exclusion predicate that ruleutils renders across several lines, which
-- the deparser has to split off the definition and put back.  The core tests
-- have no such predicate.
CREATE TABLE deparse_tests.t_exclcase (
c circle,
n int,
EXCLUDE USING gist (c WITH &&)
	USING INDEX TABLESPACE pg_default
	WHERE (CASE WHEN n > 0 THEN true ELSE false END)
	DEFERRABLE
);

-- Format-string metacharacters and embedded quotes must pass through the fmt
-- expansion inertly.  No name in the core tests contains them.
CREATE TABLE deparse_tests."evil %{name}I table" (
"a""b" int,
"%{col}s" text DEFAULT 'O''Reilly',
"100%" numeric
);

-- IF NOT EXISTS on an existing relation deparses to nothing
CREATE TABLE IF NOT EXISTS deparse_tests.t_serial (a int);

-- printing works whether or not the deparsed version is executed
SET test_ddl_deparse.execute_deparsed_ddl = off;
CREATE TABLE deparse_tests.t_printonly (a int);

-- the JSON blob itself can be printed, alone or along with the command
SET test_ddl_deparse.print_deparsed_ddl = json;
CREATE TABLE deparse_tests.t_json (id serial);
SET test_ddl_deparse.print_deparsed_ddl = 'both';
SET test_ddl_deparse.execute_deparsed_ddl = on;
CREATE TABLE deparse_tests.t_both (a int DEFAULT 42);

RESET test_ddl_deparse.print_deparsed_ddl;
RESET test_ddl_deparse.execute_deparsed_ddl;

DROP SCHEMA deparse_tests CASCADE;
