#!/usr/bin/perl
#
# Generate the errcodes_names.h header from errcodes.txt
#
# Produces ERRCODES_NAMES_COUNT, the number of SQLSTATE error codes with a
# condition name in errcodes.txt, and a lookup table mapping those codes to
# their human-readable condition names (e.g. ERRCODE_DIVISION_BY_ZERO ->
# "division_by_zero").  Codes without a condition name are omitted.
#
# The count is always visible, but the table (a static array) is only
# exposed to files that define ERRCODES_NAMES_INCLUDE_TABLE before this
# header is first included, so that widely included headers can use the
# count without dragging a copy of the table into every translation unit.
#
# Copyright (c) 2000-2026, PostgreSQL Global Development Group

use strict;
use warnings FATAL => 'all';
use Getopt::Long;

my $outfile = '';

GetOptions('outfile=s' => \$outfile) or die "$0: wrong arguments";

open my $errcodes, '<', $ARGV[0]
  or die "$0: could not open input file '$ARGV[0]': $!\n";

# Collect the named errcodes
my @names;

while (<$errcodes>)
{
	chomp;

	# Skip comments, empty lines and section headers
	next if /^#/;
	next if /^\s*$/;
	next if /^Section:/;

	die "unable to parse errcodes.txt"
	  unless /^([^\s]{5})\s+[EWS]\s+([^\s]+)(?:\s+([^\s]+))?/;

	(my $sqlstate, my $errcode_macro, my $condition_name) = ($1, $2, $3);

	# Skip lines without a condition name (duplicate codes)
	next unless defined $condition_name && $condition_name ne '';

	push @names, [ $errcode_macro, $condition_name ];
}

close $errcodes;

my $outfh;
if ($outfile)
{
	open $outfh, '>', $outfile
	  or die "$0: could not open output file '$outfile': $!\n";
}
else
{
	$outfh = *STDOUT;
}

print $outfh
  "/* autogenerated from src/backend/utils/errcodes.txt, do not edit */\n";
print $outfh "#ifndef ERRCODES_NAMES_H\n";
print $outfh "#define ERRCODES_NAMES_H\n";
print $outfh "\n";
printf $outfh "#define ERRCODES_NAMES_COUNT %d\n", scalar(@names);
print $outfh "\n";
print $outfh "#ifdef ERRCODES_NAMES_INCLUDE_TABLE\n";
print $outfh "\n";
print $outfh "typedef struct ErrCodeName\n";
print $outfh "{\n";
print $outfh "\tint\t\t\tsqlerrcode;\n";
print $outfh "\tconst char *name;\n";
print $outfh "} ErrCodeName;\n";
print $outfh "\n";
print $outfh "static const ErrCodeName errcodes_names[] = {\n";

foreach my $entry (@names)
{
	printf $outfh "\t{%s, \"%s\"},\n", $entry->[0], $entry->[1];
}

print $outfh "\t{0, NULL}\n";
print $outfh "};\n";
print $outfh "\n";
print $outfh "#endif\t\t\t\t\t\t\t/* ERRCODES_NAMES_INCLUDE_TABLE */\n";
print $outfh "\n";
print $outfh "#endif\t\t\t\t\t\t\t/* ERRCODES_NAMES_H */\n";

close $outfh if ($outfile);
